# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    sort_pub_dependencies: false
    prefer_relative_imports: true
    unawaited_futures: true
    null_check_on_nullable_type_parameter: false
    avoid_positional_boolean_parameters: false
    avoid_classes_with_only_static_members: false
    prefer_final_parameters: true
    use_key_in_widget_constructors: false
    avoid_renaming_method_parameters: false
    require_trailing_commas: true
    avoid_void_async: true
    library_private_types_in_public_api: false
    avoid_redundant_argument_values: true
    prefer_single_quotes: true
    curly_braces_in_flow_control_structures: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
