default_platform(:android)

platform :android do

  desc 'Build apk or aab'
  lane :build do |options|
    dartEnv = options[:dartEnv]
    if dartEnv == 'staging'
        buildInfo = firebase_app_distribution_get_latest_release(
          app: '1:1024984712786:android:fbea2aecb4889b552c018b',
          service_credentials_file: 'fastlane/firebase-credentials.json',
        )
        newBuildNumber = 1
        if !buildInfo.nil?
          newBuildNumber = buildInfo[:buildVersion].to_i + 1
        end
        sh("cd ../.. && flutter build apk --dart-define DART_ENV=staging --build-number=#{newBuildNumber}")
        sh("cd ../.. && mv build/app/outputs/flutter-apk/app-release.apk build/learnatgrap-staging.apk")
    elsif dartEnv == 'production'
        buildNumber = google_play_track_version_codes(
            track: 'internal',
            json_key: './fastlane/play-store-credentials.json',
            package_name: 'com.grappetite.learnatgrap'
        )
        newBuildNumber = buildNumber[0] + 1
        sh("cd ../.. && flutter build appbundle --dart-define DART_ENV=production --obfuscate --split-debug-info=build/android_split_debug_info --build-number=#{newBuildNumber}")
        sh("cd ../.. && mv build/app/outputs/bundle/release/app-release.aab build/learnatgrap-production.aab")
        sh("cd ../.. && mv build/app/outputs/mapping/release/mapping.txt build/learnatgrap-production.mapping.txt")

        [
            'arm64-v8a',
            'armeabi-v7a',
            'x86',
            'x86_64',
            ].each do |folderName|
            zip(
                path: "../build/app/intermediates/merged_native_libs/release/out/lib/#{folderName}",
                output_path: '../build/learnatgrap-production.zip',
            )
            end
    end
  end

  desc 'Deploy to Playstore or Firebase Distribution'
  lane :deploy do |options|
    dartEnv = options[:dartEnv]
    if dartEnv == 'staging'
        firebase_app_distribution(
              android_artifact_path: '../build/learnatgrap-staging.apk',
              app: '1:1024984712786:android:fbea2aecb4889b552c018b',
              groups: 'learn@grap',
              service_credentials_file: 'fastlane/firebase-credentials.json',
          )
    elsif dartEnv == 'production'
        upload_to_play_store(
                    track: 'internal',
                    json_key: './fastlane/play-store-credentials.json',
                    aab: '../build/learnatgrap-production.aab',
                    mapping_paths: [
                        '../build/learnatgrap-production.zip',
                        '../build/learnatgrap-production.mapping.txt',
                    ],
                )
    end
  end
end
